#!/usr/bin/env python3
"""Generate a structured triangular mesh for planar-guide studies."""

from __future__ import annotations

import argparse
from pathlib import Path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate a simple strip-like triangular mesh."
    )
    parser.add_argument("--output", required=True, help="Output .mesh path")
    parser.add_argument(
        "--y-max",
        type=float,
        help="Positive y truncation for the legacy uniform strip mode",
    )
    parser.add_argument(
        "--dy",
        type=float,
        help="Uniform vertical spacing for the legacy uniform strip mode",
    )
    parser.add_argument(
        "--x-left", type=float, default=-3.0, help="Left boundary x coordinate"
    )
    parser.add_argument(
        "--x-center", type=float, default=0.0, help="Center-column x coordinate"
    )
    parser.add_argument(
        "--x-right", type=float, default=3.0, help="Right boundary x coordinate"
    )
    parser.add_argument(
        "--x-values",
        default=None,
        help="Comma-separated x coordinates for a general structured rectangular grid",
    )
    parser.add_argument(
        "--y-values",
        default=None,
        help="Comma-separated y coordinates for a general structured rectangular grid",
    )
    return parser.parse_args()


def format_number(value: float) -> str:
    return f"{value:.6f}"


def generate_y_values(y_max: float, dy: float) -> list[float]:
    if y_max <= 0.0:
        raise ValueError("--y-max must be positive")
    if dy <= 0.0:
        raise ValueError("--dy must be positive")

    step_count = round((2.0 * y_max) / dy)
    if abs(step_count * dy - 2.0 * y_max) > 1.0e-9:
        raise ValueError("2*y_max must be an integer multiple of dy")

    return [(-y_max + index * dy) for index in range(step_count + 1)]


def parse_coordinate_values(raw_value: str, axis_label: str) -> list[float]:
    values = [float(token.strip()) for token in raw_value.split(",") if token.strip()]
    if len(values) < 2:
        raise ValueError(f"--{axis_label}-values must contain at least two coordinates")
    if any(values[index] >= values[index + 1] for index in range(len(values) - 1)):
        raise ValueError(
            f"--{axis_label}-values must be strictly increasing"
        )
    return values


def main() -> None:
    args = parse_args()
    if args.x_values is not None or args.y_values is not None:
        if args.x_values is None or args.y_values is None:
            raise ValueError(
                "Both --x-values and --y-values must be provided together"
            )
        x_values = parse_coordinate_values(args.x_values, "x")
        y_values = parse_coordinate_values(args.y_values, "y")
    else:
        if args.y_max is None or args.dy is None:
            raise ValueError(
                "Either provide --x-values/--y-values or the legacy --y-max/--dy pair"
            )
        y_values = generate_y_values(args.y_max, args.dy)
        x_values = [args.x_left, args.x_center, args.x_right]

    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    node_lines: list[str] = []
    triangle_lines: list[str] = []

    def node_id(row: int, column: int) -> int:
        return row * len(x_values) + column + 1

    current_node_id = 1
    for row, y_value in enumerate(y_values):
        for x_value in x_values:
            node_lines.append(
                f"node {current_node_id} {format_number(x_value)} {format_number(y_value)}"
            )
            current_node_id += 1

    current_triangle_id = 1
    for row in range(len(y_values) - 1):
        for column in range(len(x_values) - 1):
            lower_left = node_id(row, column)
            lower_right = node_id(row, column + 1)
            upper_left = node_id(row + 1, column)
            upper_right = node_id(row + 1, column + 1)

            triangle_lines.append(
                f"triangle {current_triangle_id} {lower_left} {lower_right} {upper_right}"
            )
            current_triangle_id += 1
            triangle_lines.append(
                f"triangle {current_triangle_id} {lower_left} {upper_right} {upper_left}"
            )
            current_triangle_id += 1

    header = [
        f"# {output_path.name}",
        "# Generated by scripts/generate_planar_strip_mesh.py",
        "format simple_mesh_v1",
        "dimension 2",
    ]

    content = "\n".join(header + node_lines + triangle_lines) + "\n"
    output_path.write_text(content, encoding="utf-8")


if __name__ == "__main__":
    main()
